# Generated by Django 3.2.2 on 2021-07-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(verbose_name='primary_key = True')),
                ('itemname', models.CharField(max_length=100)),
                ('itemprice', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
